version: "3"

services:
  postgres:
    container_name: your-credit-postgres
    image: postgres
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - ./postgres_data:/var/lib/postgres/data
